guardian/docs-interactive-template

src/css/_docs.scss
src/css/_mixins.scss
src/css/_youtube.scss

Small tweaks to the main video title and stand first, now all aligned (hopefully)

title and sub-header now aligned properly

---

src/js/boot.js.tpl
src/js/lib/sheettodom.js
src/js/lib/youtube.js
src/js/main.js
src/js/text/main.html

* Introduces lib `sheettodom` which fetches fields from a google sheet and populates data in the DOM based on the corresponding `data-sheet-attribute` value
* Refactor to build *shadow DOM* and then swap out loading div only when AJAX calls have completed. This tightly couples the AJAX requests with the interactive, but does reduce 'jank' of DOM mutations.
CC @akash1810

Fetch fields from Google Sheet

---

src/js/boot.js.tpl
src/js/lib/sheettodom.js
src/js/main.js

Implement suggestions of @akash1810 to push properties into app config and Google Sheet.

move sheet ID to app config and YouTube ID to Google Sheet

---

src/css/_youtube.scss
src/js/lib/youtube.js
src/js/main.js
src/js/text/main.html

Expands video after clicking play

Expands video after clicking play

---

src/css/_mixins.scss
src/css/_onward.scss
src/js/text/main.html

Adds a label tag and improves formatting for email newsletter form

updates formatting for form

---

.editorconfig
.eslintignore
.eslintrc.json
.gitignore
.jshintignore
.jshintrc
package.json
src/js/embed.js
src/js/lib/array.js
src/js/lib/boundsprojection.js
src/js/lib/fetch.js
src/js/lib/fuzzy.js
src/js/lib/jsoncache.js
src/js/lib/raf.js
src/js/lib/relative.js
src/js/lib/scrollto.js
src/js/lib/selector.js
src/js/lib/share.js
src/js/lib/sheettodom.js
src/js/lib/throttle.js
src/js/lib/youtube.js
src/js/main.js

linted js is happy js
there looks to be some unused js in the `lib` directory, which we should probably get rid of in a further PR

add eslint and jshint

---

src/css/_docs.scss
src/js/main.js
src/js/text/main.html

Logo links to bertha
About links to about
Layout fixed
and standfirst has got less code in it

sponsor now links to bertha

---

src/css/_youtube.scss
src/js/text/main.html

Much simpler implementation of the gradient. 
@duarte check if your happy with the actual gradient itself.

Main video gradient fix

---

src/css/_docs.scss
src/css/_youtube.scss
src/js/boot.js.tpl
src/js/lib/youtube.js
src/js/main.js
src/js/text/main.html

First instance of video CHAPTERS done.
Data is populated from the google sheet
Mucho tweaks to be done, @akash1810 suggested a separate PR for any cosmetic and functions (e.g playing by clicking the chapters)

Video chapters

---

src/css/_docs.scss
src/js/text/main.html

Minor tweak to the credits line height so it's now tighter.
Also removed a data attribute from the sponsor logo as it's been removed the google sheet.

Credits line height and sponsor 'undefined'

---

src/css/_docs.scss
src/css/_mixins.scss
src/css/_trailer-overlay.scss
src/css/main.scss
src/js/main.js
src/js/text/main.html

Adds the play trailer button, and overlay, plus JS to toggle the overlay on and off.
**** Missing: the actual youtube embed, which should autoplay when the trailer is shown. cc/ @gidsg  ****

Add trailer

---

src/css/_docs.scss
src/js/main.js
src/js/text/main.html

Added the trailer circle to the close item and the fade in/out
Padding and paragraph spacing is better

cleaned up the about overlay

---

src/js/boot.js.tpl
src/js/lib/emailsignupURL.js
src/js/main.js
src/js/text/main.html

Use frontend iframe for email signup. This is required in order to do a secure signup.
CC @duarte @akash1810

Use frontend iframe for email signup

---

src/css/_docs.scss
src/css/_mixins.scss
src/css/_youtube.scss

Updates play icon to remove the words 'Watch now' from the button.
Also changes hover effect to the button scale effect, and adds SVG play icon arrow.

Updates play icon

---

src/js/text/main.html

All these bits
Are now in the sheet

All the next docs elements now in the sheet

---

src/js/text/main.html

Just a text update that came in

updates the About these films box text

---

.gitignore
src/js/lib/youtube.js
src/js/main.js
src/js/text/main.html

* Play youtube trailer in overlay
* Get trailer duration from youtube API
CC @akash1810

Youtube trailer 

---

src/css/_youtube.scss

Update poster image

---

src/js/main.js
src/js/text/main.html

add click tracking for chapters and poster.
This generated link names in the format `gun-nation-chapters | The gun owners` for chapters.

add click tracking for chapters and poster

---

src/js/lib/youtube.js

* Remove expand animation on mobile
* Turn off related content end slate
CC @akash1810 @duarte

Don't expand player on mobile

---

src/css/_docs.scss
src/js/main.js
src/js/text/main.html

The body of the about overlay no longer closes it.

Close about overlay fixed

---

src/js/main.js
src/js/text/main.html

Fixes https://github.com/guardian/docs-interactive-template/issues/44

Fixed innerHTML baddness

---

src/js/text/main.html

* remove share count
* add email share option
CC @duarte @mr-mr @akash1810

remove share count add email share

---

src/css/_docs.scss

Left aligns social media buttons & moves them 1px closer together

Microest micro change

---

src/css/_docs.scss
src/css/_mixins.scss
src/css/_onward.scss
src/css/_trailer-overlay.scss
src/css/_youtube.scss
src/js/text/main.html

This tightens up a lot of the spacing, mostly in the email signup section.

Loads of small design tweaks

---

src/css/_youtube.scss

fixes https://github.com/guardian/docs-interactive-template/issues/57
****

fixes large screen video fullscreen issue

---

src/css/_docs.scss
src/js/lib/youtube.js
src/js/main.js

Adds a progress bar to the chapters top border

Adds a progress bar to chapters

---

src/js/main.js

add title attribute to chapter li for tooltip

---

src/js/text/main.html

...better late than never
CC @akash1810

add click tracking to trailer link

---

src/js/text/main.html

Updates description text for the "coming soon" container

"Coming soon" text update

---

src/js/lib/youtube.js

to ensure the YT JS has is loaded before proceeding

wrap youtube-iframe-player init function in a promise

---

src/js/lib/youtube.js

Reverts guardian/docs-interactive-template#66
😢

Revert "wrap youtube-iframe-player init function in a promise"

---

src/js/lib/detect.js
src/js/lib/youtube.js

Extract it into its own module, keeps youtube.js clean.

refactor isMobile function

---

src/js/lib/tracking.js
src/js/lib/youtube.js

keeps youtube.js simple and easier to reason about

tracking module

---

src/js/lib/dom.js
src/js/lib/sheettodom.js
src/js/main.js

creating a setAttributes function in its own module

refactoring

---

package.json
src/js/config.js
src/js/lib/dom.js
src/js/lib/youtube.js

branched off of #74 (that needs to be merged in before this gets reviewed)
[youtube-player](https://github.com/gajus/youtube-player) wraps the loading of the yt api in a promise, so it should be fully loaded before we do anything with it.
It also supports multiple players.

replace youtube-iframe-player with youtube-player

---

src/css/_youtube.scss

GIF with a throttled connection to exaggerate the result:

loading... whilst awaiting youtube iframe

---

src/js/boot.js.tpl

change const to var fix safari

---

src/css/_continue-watching.scss
src/js/lib/relative.js
src/js/lib/throttle.js
src/js/main.js
src/js/text/main.html

Makes the 'more documentaries' container title link to the new [documentaries series page](https://www.theguardian.com/documentaries)

Link to series page

---

package.json
src/js/config.js
src/js/main.js

😢 https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility

use lodash find because find isn't supported by IE11

---

src/css/_youtube.scss
src/js/main.js

Small change to speed up autoplay
cc/ @akash1810 @gidsg

Speed up autoplay timer

---

src/js/lib/sheetURL.js

This should mean faster updates but we do risk accidental edits going live.
Fixes #106

use docsdata-test sheet

---

src/css/_youtube.scss

remove a style that's not needed and breaks Android webview

---

src/css/_coming-soon.scss
src/css/_general.scss
src/css/_youtube.scss
src/css/info.scss

Imports some of the design tweaks originally made for original dramas

Import some original drama design

---

src/js/boot.js.tpl
src/js/lib/sheetNameFromShortId.js

Adding placeholder links for the April docs
@gidsg

Adds links to new docs

---

src/js/boot.js.tpl

Charlie needs this update so the page for The Island can be subedited. There will likely be another PR to update the link after subediting is done and we have a final link…

edits the island link before subediting

---

README.md

should make it simpler to pick up this project

make readme more expressive

---

src/js/boot.js.tpl
src/js/lib/sheetNameFromShortId.js

Added the island and updated valley rebels url

Lisa villani patch 2

---

src/js/boot.js.tpl
src/js/lib/sheetNameFromShortId.js

Update now Valley Rebels is live.

update live URL and next doc as fallback

---

src/js/lib/sheetNameFromShortId.js

New Fallback URL

---

src/js/boot.js.tpl

Updated Sprinters factory url to live one

Updated Sprinters factory

---

src/js/lib/sheetNameFromShortId.js

Updating fallback url page to the-infamous-chalk-girl for next doc page

Change default to the-infamous-chalk-girl

---

src/js/boot.js.tpl

Adding provisional fish-story url. Hope I've done it correctly!

Adding provisional fish-story url

---

src/js/lib/sheetNameFromShortId.js

Changing fallback url from the-infamous-chalk-girl to fish-story. Once again hope it's correct!

Updating fallback url

---

src/js/lib/sheettodom.js
src/js/main.js

because callbacks are so last year
this is prep work for moving to a single tabbed sheet for better reliability with the visuals tool

switch to using the promise pattern

---

src/js/lib/sheetURL.js

Probs should have suggested this change in earlier PR but better late than never!

use prod sheet

---

src/js/boot.js.tpl

Updated fish-story
Added pitching-up
Cheers

Amending and adding doc urls

---

src/js/lib/sheetNameFromShortId.js

Updates fall back url to Pitching up
Cheers

Updates fall back url to Pitching up

---

src/js/boot.js.tpl

Adding dearborn-michigan documentary
cheers

Adding dearborn-michigan documentary

---

src/js/lib/sheetNameFromShortId.js

Adding dearborn-michigan as fallback url. hopefully done it correctly!
Thanks

Adding dearborn-michigan as fallback url

---

src/js/lib/sheetNameFromShortId.js

Updates fallback to second innings. Same old!
Cheers

Updates fallback to second innings

---

src/js/boot.js.tpl

updates michigan url

---

src/js/boot.js.tpl

Adding second innings doc plus updating dearborn michigan to the live url 
Hopefully correct this time!
Cheers

Tries to add second innings again

---

src/js/boot.js.tpl

similar to https://github.com/guardian/docs-interactive-template/pull/142 but without the merge conflict

update pitching up

---

src/js/boot.js.tpl

Updates second innings url plus adds preliminary urls for forthcoming qandeel-baloch and home-games documentaries!

Updates second innings url plus adds two more doc urls

---

src/js/lib/sheetNameFromShortId.js

Adding qandeel-baloch fallback url for next doc.
Cheers

Updates fallback url

---

src/js/lib/sheetNameFromShortId.js

the qandeel doc has been renamed

update doc name

---

src/js/boot.js.tpl

sorry forgot. i need to change qandeel slug too as the baloch was dropped

updates qandeel

---

src/js/boot.js.tpl

updating qandeel to live url
updating next doc name to correct home-match
cheers

Updates qandeel url

---

src/js/boot.js.tpl

Updates home match url to live
Adds new doc muxes
Cheers!

Updates home match url to live

---

src/js/lib/sheetNameFromShortId.js

updates fallback to new doc muxes

---

src/js/boot.js.tpl

And updating Muxes to live url

Adding new documentary on the road

---

src/js/lib/sheetNameFromShortId.js

updates to latest doc

---

src/js/boot.js.tpl

adding new doc

---

src/js/boot.js.tpl

Changes to killing-gävle

---

src/js/lib/sheetNameFromShortId.js

Changes fallback to killing-gävle

---

src/js/boot.js.tpl

Updates killing gavle url

---

src/js/boot.js.tpl

Sprry Akash Conectifai is now just one n!

Changes name of new doc as had been mispelled

---

src/css/_coming-soon.scss
src/css/_continue-watching.scss
src/js/text/main.html

Just made a few changes to the docs-interactive page!

updates styling to docs-interactive

---

src/js/boot.js.tpl

Adding new doc and updating connectifai url to live
Cheers!

Adding next documentary

---

src/js/boot.js.tpl

Sorry Akash! I left conectifai spelt incorrectly with two n's hence it's not working now the fallback url has changed!

Removes one of the n's from conectifai

---

src/js/boot.js.tpl

adds new doc white-fright and amends pearl url

---

src/js/lib/sheetNameFromShortId.js

updates fallback url to new doc white-fright

---

src/js/boot.js.tpl

and adds Four Weddings provisional url
hopefully!

Updates The Climate and The Cross url

---

src/js/lib/sheetNameFromShortId.js

Adds new fallback url for the new doc four weddings

---

src/js/boot.js.tpl

Reverts guardian/docs-interactive-template#184

Revert "Updates our house url and adds new doc"

---

src/js/lib/sheetNameFromShortId.js

Reverts guardian/docs-interactive-template#185

Revert "changes fallback url to latest doc"

---

src/js/boot.js.tpl

Adds new doc

---

src/js/boot.js.tpl

Adds white fright

---

src/js/boot.js.tpl

little pyongyang and cops and robbers

adds two more new docs

---

src/js/boot.js.tpl

adds silent sam doc

---

src/js/boot.js.tpl

Updates Silent Sam url

---

src/js/boot.js.tpl

adds skip day final url

---

src/js/boot.js.tpl

updates crisanto street url

---

src/js/boot.js.tpl

adds fighting shame

---

src/js/boot.js.tpl

adds the trial url

---

src/js/boot.js.tpl

updates where the river runs red url

adds  someone-elses-war

---

src/js/boot.js.tpl

adds lasting marks

---

src/js/boot.js.tpl

and adds anonymous-comes-to-town and sam-and-the-plant-next-door documentaries

updates lasting marks url

---

src/js/boot.js.tpl

adds trapped-in-the-city-of-a-thousand-mountains

---

Gruntfile.js
src/js/boot.js.tpl
src/js/lib/sheetNameFromShortId.js

Changes to docs player for Crannog & Share

Crannog & Share

---

src/css/main.scss

Dw doc dcr update

---

src/css/_youtube.scss
src/js/boot.js.tpl
src/js/lib/sheetNameFromShortId.js

Dw doc outlaws ocean
