src/css/_mixins.scss

On expanding the stand first, the minus icon was sticking out to the left on leftCol and above. It's not now.

removed redundant code on minus icon

---

src/css/_docs.scss
src/js/main.js
src/js/text/main.html

Psych! The credits are in exactly the same place as they were before. But they now load from a separate column in the google spreadsheet. Party time.

Move credits

---

src/css/_docs.scss

Stand-first has a fixed padding-bottom instead of s percentage.

Removed percentages on standfirst height

---

src/css/_youtube.scss
src/js/lib/youtube.js
src/js/text/main.html

Each chapter element is now a button, initialising play and skipping to the relevant timestamp.
The player is also initialised on load, rather than on play, so both the big yellow button and the chapters have something to aim for.

Chapter button play

---

src/css/_docs.scss

Charlie put in a chapter that was over 2 lines and made me go in and fix the alignment.
Another PR would be to auto set the height and add that space to the expand video, so the chapters don't get cut off.

chapters now align top

---

src/js/lib/youtube.js

e.g. `1:1` changes to `1:01`
CC @akash1810

pad out duration to 2 digits

---

src/js/lib/share.js
src/js/main.js

This attempts to simplify the share options, to require minimal configuration and be closer to the current behaviour of Frontend.
* Use OG markup for Facebook 
* Use title from config for Twitter
CC @akash1810

simplify share options

---

src/css/_docs.scss

This adds the top border back to inactive chapters, so the text doesn't jump down 1px when they become active.

Add top border back to inactive chapters

---

.eslintrc.json
package.json
src/js/config.js
src/js/lib/youtube.js

Mirror most playback events currently sent by VideoJS, namely:
* `content:video:play`
* `content:video:25`
* `content:video:50`
* `content:video:75`
* `content:video:end`
Note: I don't expect this to appear in Ophan frontend but it should be queryable in the data lake.
CC @akash1810 @emma-p

Playback tracking

---

src/css/_youtube.scss

We're already setting the `background-image` [in js](https://github.com/guardian/docs-interactive-template/blob/aa-poster-image/src/js/main.js#L110) with a value from the sheet. Setting it via css just overrides this and doesn't make it dynamic, which is bad.

do not set poster image in css

---

src/js/lib/dom.js
src/js/lib/youtube.js
src/js/main.js

branched off of https://github.com/guardian/docs-interactive-template/pull/72 (that needs to be merged in before this gets reviewed)
- `initChapters` function in main.js to encapsulate the chapter operations.
- keep `.filter` operation clean; move percentage progress calculation outside of `.filter`. Also removes a dodgy `let`.

chapter refactor

---

package.json

to avoid the warnings when trying to deploy

explicitly add grunt-aws dep

---

src/js/lib/youtube.js
src/js/main.js

Currently, the click event handler for `.docs_poster--loader` is attached once the YouTube player is ready. This means interaction to the element is blocked until the js is downloaded, so early clicks are lost.
This changes the behaviour. Now, the click event handler is bound early and it invokes the download of the YouTube js. This means you can interact with the `.docs_poster--loader` element as soon as the page loads, rather than having to wait until the js is loaded.

bind click handler early

---

src/js/lib/youtube.js

The first chapter li has a start time of 0. JavaScript is fun: `if (0)` is false...
```js
const seconds = 0;
if (seconds) {
console.log('You will never get here!');
}
```
Checking if `seconds` is not `undefined` is better.

fix chapter 1 click handler

---

.jshintrc
src/js/boot.js.tpl
src/js/lib/tracking.js

couldn't get babel plugin working, so just using the polyfill provided by mdn (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill)
will replace once I've got the babel plugin working

crude polyfill for object.assign

---

src/css/_youtube.scss

Reverts guardian/docs-interactive-template#89
its broken in firefox as it doesn't disappear:

Revert "loading... whilst awaiting youtube iframe"

---

package.json
src/js/config.js
src/js/lib/sheettodom.js

because String.prototype.startsWith isn't supported in IE11
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Browser_compatibility

use lodash startswith

---

src/js/main.js

missing an argument in the [constructor](https://github.com/guardian/docs-interactive-template/blob/aa-fix-tracking/src/js/lib/youtube.js#L41) caused bad things to happen
currently on https://www.theguardian.com/world/ng-interactive/2017/jan/06/radical-brownies-berets-badges-and-social-justice-video

fix tracking

---

src/js/lib/emailsignupURL.js

Previously the apps were getting the CODE sign-up URL as they don't have the same `window.location.origin` as web.

use PROD URL for email signup in apps

---

src/js/lib/sheettodom.js
src/js/lib/youtube.js
src/js/main.js

Fixes a couple of JS errors with `pub-original-drama` branch
* player is not defined
* don't fetch snap links if not defined in sheet
I suspect (but don't know for sure) that these will fix the issues in the iOS webview

fix assorted JS errors

---

src/js/lib/youtube.js

The youtube iframe doesn't appear to be in a `playing` state when video progress === video duration. Instead, the player state transitions to `ended`.
See https://developers.google.com/youtube/iframe_api_reference#Events

fix player end tracking

---

src/js/lib/tracking.js

This is to provide a hook to allow Ophan to differentiate Atoms from other media events. 
Ideally the thrift definition would allow for a platform value. But without this we only have the `mediaId` to play with.
CC @obrienm 
Example event:

add interactive prefix to ophan media events

---

src/js/lib/docs-coming-soon.js
src/js/lib/docs-supporter.js
src/js/lib/dom.js
src/js/main.js
src/js/text/main.html

Reads the following fields from the sheet:
- showSupported: TRUE|FALSE used to determine whether to render the supported by elements
- supportedBadgeUrl: URL url to supported badge image
- supportedSiteUrl: URL url to link to when clicking on supportedBadgeUrl
- supportedInfo: HTML text to show in the supported by modal
- isBertha: TRUE|FALSE used to determine whether to render the sub-heading in the coming soon section
The supported block is now added to the DOM with javascript. Default is to add it. It is not added iff `showSupported === 'FALSE'`.
The other fields have sensible defaults to Bertha values.
When `showSupported === 'FALSE'`:

adds support for configuring supported by in the sheet

---

src/js/main.js

falls back to sheet title if `window.guardian` doesn't exist for whatever reason

use headline field as share text

---

src/js/lib/docs-supporter.js
src/js/lib/sheetData.js
src/js/lib/sheettodom.js
src/js/main.js

- abstracts away json structure
- use getters to access metadata fields
- defaults data where necessary
Also results in a better failure case; if we can't find any metadata, we `console.log` (if `window.console` is available). We also do not break rendering, instead we render a slightly nicer:

refactor doc metadata into a class

---

src/js/text/main.html

change the href to a full URI, as relative URLs don't work in the iOS app

update more documentaries link

---

src/js/boot.js.tpl

If no require variable is in scope, fallback to use curl if we have it.
Apps no longer have require in the window scope, but do have curl.
This change should hopefully fix the issue on apps and not require releases.

Use curl if require is not in scope

---

src/css/_youtube.scss

This prevents the YouTube poster image on documentary pages (e.g. [Black Sheep](https://www.theguardian.com/news/ng-interactive/2018/oct/26/black-sheep-the-black-teenager-who-made-friends-with-racists-video)) in the iOS app from being inverted when a user has enabled [Smart Invert](https://support.apple.com/en-gb/HT207025) on their Apple device. 
To see the problem, switch on Smart Invert on your device (Settings -> General -> Accessibility -> Display Accommodations -> Invert Colours -> Smart Invert) and open the above documentary link in the Guardian app.

Don't invert YouTube poster image in iOS app

---

.editorconfig
cfg/s3.json
src/css/_continue-watching.scss
src/css/_doc-cards.scss
src/css/main.scss
src/js/lib/sheetData.js
src/js/lib/sheetNameFromShortId.js
src/js/lib/sheetURL.js
src/js/main.js
src/js/text/main.html

This removes dependency on [doc-cards](https://github.com/guardian/doc-cards) for onward journeys by pulling in a poster image, logline and link from the documentaries sheet instead.

New onward journey links

---

harness/dcr-immersive.html
package.json

Fixes the immersive DCR harness. Longer-term we should deprecate this repo once we have an immersive video layout.
cc @HarryFischer

Fix dcr harness

---

src/js/text/main.html

Add the title attribute to the sign up iframe, as it an accessibility issue.
🤷 
Resolves: https://github.com/guardian/dotcom-rendering/issues/4454
N/A
N/A
-   [X] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader) By DAC
-   [X] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [X] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [X] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

fix(a11y): add title to iframe

---

src/css/info.scss
src/js/main.js
src/js/text/main.html

Accessibility fixes for this page: https://www.theguardian.com/world/ng-interactive/2022/aug/22/little-warrior-the-boxer-breaking-away-from-venezuelan-poverty-documentary 
- 'full description' button, changed from a div to a button to allow keyboard navigation, updated description to indicate open and closed state and position moved above content, so that the keyboard flows down the age to the content next after opening
- Created id link to 'maincontent' of the page to allow users to skip the navigation
- Cards at the bottom of the page, added alt for image, added description to links 
- Added a H1 to the page 
- Added aria-labels to share links

Accessibility fix
